### ISSUE TITLE
Display cover image on node

### ISSUE THREAD

**Issue by AJamesPhillips** [centerofci/data-curator2#118]
### Currently
* Images can be embedded into text using markdown but not used as cover images

### Description (acceptance criteria)
- [x] Add an optional string field to all wcomponents of `summary_image` https://github.com/centerofci/data-curator2/blob/master/app/frontend/src/shared/wcomponent/interfaces/base.ts
- [x] Add this to the wcomponent form, probably lower down near the section on label color.
- [x] Display the image on the node in the canvas in some way.
  * Preferably do not use a material-ui component to keep it vanilla so that the css for the canvas is as "straightforward" as possible.
- [x] If the image is wider than the node width then scale it down.
- [x] If the image is taller than some value, also limit its vertical height and scale it down.  Perhaps limit it to 70% of the maximum width (or less / more, depending on what you think is aesthetically appealing).
- [x] If the user clicks on the image they should open the node.
- [ ] optionally, on hover provide a "full screen icon" such as a small text box saying "open" in the top right corner of the image which when clicked opens the image in a new tab and calls `stopImmediatePropagation` on the click event.

* Note: we do not allow people to upload images.  For now they must use images from a separate file store such as wikipedia: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Mother_%26_Daughter_%2830717330985%29.jpg/1024px-Mother_%26_Daughter_%2830717330985%29.jpg

### Why (hypothesis)
* Will give users the opportunity to more easily insert images into their plans / diagrams.
* Will give consumers stronger mental anchors within the map to help more easily orientate themselves.
* Images can provide powerful semantics at a propositional, emotional, perspectival level.

### Additional context
This is how it looks in Trello:
![image](https://user-images.githubusercontent.com/526509/131352302-f80364d7-4399-4320-9b58-669ceee412f1.png)

**Comment by pegnott** [comment]
All functionality except the optional hover have been implemented.

**Comment by AJamesPhillips** [comment]
This looks great.  Closing.
