### ISSUE TITLE
When in presenting, make icon look more prominent

### ISSUE THREAD

**Issue by AJamesPhillips** [centerofci/data-curator2#124]
### Currently
* The icon for presenting is greyed out when in presenting mode

### Description (acceptance criteria)
- [ ] when in presenting, make the icon more obvious

### Why (hypothesis)
* Will be less confusing to users.

### Additional context
When editing it currently looks like:
![image](https://user-images.githubusercontent.com/526509/131850891-9d9c4f12-cca5-41d6-9ab0-40040ec21307.png)
When presenting it currently looks like:
![image](https://user-images.githubusercontent.com/526509/131851265-6e19dce3-4957-4d71-ade9-46b298fa52d2.png)

**Comment by pegnott** [comment]
I have added a file containing a material makestyles which allow for the inversion of the appearance of enabled/disabled buttons. 
https://github.com/centerofci/data-curator2/blob/50fd21ac9b8ee7995fdbbae90b993555d8d08db1/app/frontend/src/ui_themes/invert_disabled.tsx

And updated relevant components to implement it, an example can seen here:
https://github.com/centerofci/data-curator2/blob/50fd21ac9b8ee7995fdbbae90b993555d8d08db1/app/frontend/src/views/ViewOptions.tsx

notably:
setting a class from the imported makeStyles: 
https://github.com/centerofci/data-curator2/blob/50fd21ac9b8ee7995fdbbae90b993555d8d08db1/app/frontend/src/views/ViewOptions.tsx#L26

and applying the class to the element:
https://github.com/centerofci/data-curator2/blob/50fd21ac9b8ee7995fdbbae90b993555d8d08db1/app/frontend/src/views/ViewOptions.tsx#L33

![image](https://user-images.githubusercontent.com/11094740/132053788-6d7f4b17-8be8-431c-a369-b44e0c232d71.png)

**Comment by pegnott** [comment]
closing
