### ISSUE TITLE
Display a help menu

### ISSUE THREAD

**Issue by AJamesPhillips** [centerofci/data-curator2#135]
### Currently
* A list of the commands would be useful.

### Description (acceptance criteria)
- [x] Pressing `?` should show a modal with a list of commands.
- [x] Do not trigger modal when editing text (use `user_activity.is_editing_text` flag
- [x] Style menu and help text

### Why (hypothesis)
* Will make it easier for users to understand the available commands and how to use the application.

**Comment by pegnott** [comment]
styles added: 
![image](https://user-images.githubusercontent.com/11094740/132704191-5208e54b-7159-4b19-a180-ca13c2e03787.png)
