### ISSUE TITLE
UI polish

### ISSUE THREAD

**Issue by AJamesPhillips** [centerofci/data-curator2#144]
- [x] Increase width of input fields to accommodate values of 255
![image](https://user-images.githubusercontent.com/526509/132746936-166cca45-5324-47e0-88fa-96506f918739.png)

- [x] Hide hours and minutes when set to Days time resolution
- [ ] Hide minutes when set to Hours time resolution
(More thorough specification [of one of](https://github.com/centerofci/data-curator2/issues/117#issuecomment-910324191) these comments)
![CCI___Data_Curator](https://user-images.githubusercontent.com/526509/132745303-778726d3-a2f4-4e97-8ccf-840add79f337.png)

- [x] When in presentation mode, do not show the placeholder text for an empty datetime input field:
![image](https://user-images.githubusercontent.com/526509/132747582-a5a7100d-fbdf-4f32-b1e3-0b195ed78cbb.png)

- [ ] For the WComponent's the invariant date should be set to the created_at date (and this should **not** be editable).
- [ ] If the date is edited and it is different to the invariant date then set the custom_created_at.
- [ ] If the date is edited and it is same as the invariant date then set the custom_created_at to undefined, i.e. delete it.

- [x] Do not show the function to copy and paste the datetime when in presentation mode
![CCI___Data_Curator](https://user-images.githubusercontent.com/526509/132746589-7b9d356e-a4c1-4fc3-a49b-3951b909941a.png)

- [ ] If you put a datetime into the datetime edit box and then click the copy/paste button it doesn’t seem to show anything.  Is this intentional?

https://user-images.githubusercontent.com/526509/132747614-aee14ced-a367-4f86-921e-e61436e48df0.mov

**Comment by pegnott** [comment]
` If you put a datetime into the datetime edit box and then click the copy/paste button it doesn’t seem to show anything. Is this intentional?`

Yes.

**Comment by pegnott** [comment]
` For the WComponent's the invariant date should be set to the created_at date (and this should not be editable).`

This is part of the source of my confusion about invariant date. why are non-editable values being put within a ui for editing values?

**Comment by pegnott** [comment]
`Hide minutes when set to Hours time resolution`

I am checking to see if this is possible via various means. if it is not, is showing this value as 00 a reasonable solution? if not, a datetime input isn't going to work.

**Comment by pegnott** [comment]
> `Hide minutes when set to Hours time resolution`
> 
> I am checking to see if this is possible via various means. if it is not, is showing this value as 00 a reasonable solution? if not, a datetime input isn't going to work.

Note: I can def hide hours and minutes by way of using a date vs datetime element, not a problem.
i am checking on my ability to either change the display format or otherwise meet the desire to hide minutes when time res is set to hour, and checking if showing 00 values there is a reasonable alternative if we can't.

**Comment by pegnott** [comment]
`When in presentation mode, do not show the placeholder text for an empty datetime input field:`
the datetime input field does not honor placeholder values. i am looking into ways to get around this, however I don't think it should be done addressed within the datetime component.

**Comment by AJamesPhillips** [comment]
> https://github.com/centerofci/data-curator2/issues/144#issuecomment-916907077

Ok thanks.  Can we add value it is current set to (using logic of: `value || invariant_value`) so that a user can select and copy and then paste into another datetime field.  When clicking into the field it should also selected all the text in the text box like this:


https://user-images.githubusercontent.com/526509/132867498-04445261-53bd-4575-899d-e3e607bebb44.mov

**Comment by AJamesPhillips** [comment]
I'm happy we've found a solution to these.
