### ISSUE TITLE
Animate the hide/show time sliders pane

### ISSUE THREAD

**Issue by AJamesPhillips** [centerofci/data-curator2#153]
### Currently
* The pane just jumps from visible to invisible and visa versa.

### Description (acceptance criteria)
- [x] Pressing the "hide / show time sliders" toggle button animates the hiding and showing of the pane

### Why (hypothesis)
* Will match the hide/show of the side panel.

**Comment by pegnott** [comment]
The only comment/suggestion I have there is that we could consider moving the sliders above the buttons. that way the show/hide button would still be under the mouse, similar to the side panel open/close. Comparison videos:


https://user-images.githubusercontent.com/11094740/133312943-d39eb20c-b0d4-4e99-b7e5-62ce665bf118.mov


https://user-images.githubusercontent.com/11094740/133312962-6a1f9025-ccab-43b6-bb67-7053620429fa.mov

**Comment by AJamesPhillips** [comment]
Thanks Peg.  (Done with https://github.com/centerofci/data-curator2/pull/154 )
