### ISSUE TITLE
Show HelpMenu infront of SidePanel

### ISSUE THREAD

**Issue by AJamesPhillips** [centerofci/data-curator2#155]
### Describe the bug
Pressing `?` shows the help menu in its modal but it is displayed behind the side panel.

### To Reproduce
1. Go to http://localhost:8080/app
2. Press `?`
3. See the HelpMenu is displayed behind the side panel

### Expected behavior
Display in front of the side panel.

### Screenshots
![image](https://user-images.githubusercontent.com/526509/133446847-5d27002b-15a7-4b94-9a89-f0e2ca950043.png)

**Comment by pegnott** [comment]
![image](https://user-images.githubusercontent.com/11094740/133449083-b1d314eb-751b-4845-9fe3-3f20144d0179.png)
